name: 'Export secrets from environment variables with a prefix'
description: ''
inputs:
  repo:
    required: false
    default: ${{ github.repository }}
    description: ''
  secrets-prefix:
    required: true
    description: ''
  secrets-type:
    required: false
    default: 'org'
    description: ''
  environment-name:
    required: false
    default: ''
    description: ''
  artifact-name:
    required: true
    description: ''
runs:
  using: composite
  steps:
    - shell: pwsh
      name: Export secrets from environment variables with prefix '${{ inputs.secrets-prefix }}'
      run: >
        ${{ github.action_path }}/scripts/export-secrets-from-env.ps1
        ${{ inputs.repo }}
        ${{ runner.temp }}/${{ inputs.artifact-name }}.csv
        ${{ inputs.secrets-prefix }}
        ${{ inputs.environment-name }}

    - uses: actions/upload-artifact@v3.1.2
      name: Upload secrets file
      with:
        name: ${{ inputs.artifact-name }}
        if-no-files-found: error
        retention-days: 1
        path: ${{ runner.temp }}/${{ inputs.artifact-name }}.csv
        