name: Export Secrets to Artifact

on:
  workflow_dispatch:

env:
  PREFIX_SECRETS: 'SECRETS_'
jobs:
  parse-repo-name:
    name: Parse Repository Name
    runs-on: windows-latest
    outputs:
      owner: ${{ steps.parse-repo-name.outputs.owner }}
      repository: ${{ steps.parse-repo-name.outputs.repository }}
    steps:
      - name: Parse Repository Name
        id: parse-repo-name
        uses: martins-vds/gh-migration-scripts/composite-actions/parse-repository-name@main
        with:
          repository: ${{ github.repository }}
  export-repo-secrets:
    name: Export Repo Secrets
    runs-on: windows-latest
    needs: [parse-repo-name]
    steps:
      - name: Export Repo Secrets
        uses: martins-vds/gh-migration-scripts/composite-actions/export-secrets@main        
        env:
          '${{ env.PREFIX_SECRETS }}MY_SECRET': ${{ secrets.MY_SECRET }}
        with:
          secrets-prefix: ${{ env.PREFIX_SECRETS }}
          secrets-type: 'repo'
          artifact-name: 'secrets-${{ needs.parse-repo-name.outputs.owner }}-${{ needs.parse-repo-name.outputs.repository }}'
  export-env-secrets:
    name: Export Environment Secrets from Production
    runs-on: windows-latest
    needs: [parse-repo-name]
    environment: production
    steps:
      - name: Export Environment Secrets
        uses: martins-vds/gh-migration-scripts/composite-actions/export-secrets@main               
        env:
          '${{ env.PREFIX_SECRETS }}MY_PROD_SECRET': ${{ secrets.MY_PROD_SECRET }}
        with:
          secrets-prefix: ${{ env.PREFIX_SECRETS }}
          secrets-type: 'env'
          artifact-name: 'secrets-${{ needs.parse-repo-name.outputs.owner }}-${{ needs.parse-repo-name.outputs.repository }}-production'
          environment-name: production

  merge-secrets:
    name: Merge Secrets
    runs-on: windows-latest
    needs: [ parse-repo-name, export-repo-secrets, export-env-secrets]
    steps:
      - uses: actions/download-artifact@v3.0.2
        name: Download Secret Artifacts
        with:
          path: ${{ runner.temp }}/secrets/all
      - name: Merge Secrets
        uses: martins-vds/gh-migration-scripts/composite-actions/merge-csv-files@main
        with:
          path: ${{ runner.temp }}/secrets/all
          output-file: ${{ runner.temp }}/secrets/merged/secrets-${{ needs.parse-repo-name.outputs.owner }}-${{ needs.parse-repo-name.outputs.repository }}-merged.csv
      - uses: actions/upload-artifact@v3.1.2
        name: Upload Merged Secrets
        with:
          name: secrets-${{ needs.parse-repo-name.outputs.owner }}-${{ needs.parse-repo-name.outputs.repository }}-merged
          path: ${{ runner.temp }}/secrets/merged/secrets-${{ needs.parse-repo-name.outputs.owner }}-${{ needs.parse-repo-name.outputs.repository }}-merged.csv