name: Export Secrets to Artifact

on:
  workflow_dispatch:

env:
  REPO_SECRETS_PREFIX: 'REPO_SECRETS_'
  ENV_SECRETS_PREFIX: 'ENV_SECRETS_'
  GITHUB_ENVIRONMENT: 'Dev'
jobs:
  export-repo-secrets:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Export Repo Secrets
        uses: martins-vds/goa-gh-migration/composite-actions/export-secrets@master        
        env:
          '${{ env.REPO_SECRETS_PREFIX }}MY_SECRET': ${{ secrets.MY_SECRET }}
        with:
          secrets-prefix: ${{ env.REPO_SECRETS_PREFIX }}
          artifact-name: 'secrets'
  export-env-secrets:
    runs-on: windows-latest
    environment: ${{ github.env.GITHUB_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Export Environment Secrets
        uses: martins-vds/goa-gh-migration/composite-actions/export-secrets@master        
        env:
          '${{ env.ENV_SECRETS_PREFIX }}MY_DEV_SECRET': ${{ secrets.MY_DEV_SECRET }}
        with:
          secrets-prefix: ${{ env.ENV_SECRETS_PREFIX }}
          artifact-name: 'secrets'
          environment-name: ${{ env.GITHUB_ENVIRONMENT }}
