name: Export Secrets to Artifact

on:
  workflow_dispatch:

env:
  PREFIX_SECRETS: 'SECRETS_'
jobs:
  export-repo-secrets:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Parse Repository Name
        id: parse-repo-name
        uses: martins-vds/gh-migration-scripts/composite-actions/parse-repository-name@main
        with:
          repository: ${{ github.repository }}
      - name: Export Repo Secrets
        uses: martins-vds/gh-migration-scripts/composite-actions/export-secrets@main        
        env:
          '${{ env.PREFIX_SECRETS }}MY_SECRET': ${{ secrets.MY_SECRET }}
        with:
          secrets-prefix: ${{ env.PREFIX_SECRETS }}
          artifact-name: 'secrets-${{ steps.parse-repo-name.outputs.owner }}-${{ steps.parse-repo-name.outputs.repository }}'
  export-env-secrets:
    runs-on: windows-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Parse Repository Name
        id: parse-repo-name
        uses: martins-vds/gh-migration-scripts/composite-actions/parse-repository-name@main
        with:
          repository: ${{ github.repository }}
      - name: Export Environment Secrets
        uses: martins-vds/gh-migration-scripts/composite-actions/export-secrets@main               
        env:
          '${{ env.PREFIX_SECRETS }}MY_PROD_SECRET': ${{ secrets.MY_PROD_SECRET }}
        with:
          secrets-prefix: ${{ env.PREFIX_SECRETS }}
          artifact-name: 'secrets-${{ steps.parse-repo-name.outputs.owner }}-${{ steps.parse-repo-name.outputs.repository }}-production'
          environment-name: production
