name: Export Secrets to Artifact

on:
  workflow_dispatch:

env:
  REPO_SECRETS_PREFIX: 'REPO_SECRETS_'
  ENV_SECRETS_PREFIX: 'ENV_SECRETS_'
  GITHUB_ENVIRONMENT: 'production'
jobs:
  export-repo-secrets:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Parse Repository Name
        id: parse-repo-name
        uses: martins-vds/gh-migration-scripts/composite-actions/parse-repository-name@main
      - name: Export Repo Secrets
        uses: martins-vds/gh-migration-scripts/composite-actions/export-secrets@main        
        env:
          '${{ env.REPO_SECRETS_PREFIX }}MY_SECRET': ${{ secrets.MY_SECRET }}
        with:
          secrets-prefix: ${{ env.REPO_SECRETS_PREFIX }}
          artifact-name: 'secrets-${{ steps.parse-repo-name.outputs.owner }}-${{ steps.parse-repo-name.outputs.repository }}'
  export-env-secrets:
    runs-on: windows-latest
    environment: ${{ github.env.GITHUB_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Parse Repository Name
        id: parse-repo-name
        uses: martins-vds/gh-migration-scripts/composite-actions/parse-repository-name@main
      - name: Export Environment Secrets
        uses: martins-vds/gh-migration-scripts/composite-actions/export-secrets@main        
        env:
          '${{ env.ENV_SECRETS_PREFIX }}MY_PROD_SECRET': ${{ secrets.MY_PROD_SECRET }}
        with:
          secrets-prefix: ${{ env.ENV_SECRETS_PREFIX }}
          artifact-name: 'secrets-${{ steps.parse-repo-name.outputs.owner }}-${{ steps.parse-repo-name.outputs.repository }}-${{ env.GITHUB_ENVIRONMENT }}'
          environment-name: ${{ env.GITHUB_ENVIRONMENT }}
